### ISSUE TITLE
[DEFECT] Confusing response to bad input to create_componentsets_in_HERON function

### ISSUE THREAD

**Issue by caleb-sitton-inl** [idaholab/FORCE#15]
### Thank you for the defect report

- [X] I am using the latest version of `FORCE`.
- [x] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

If the `FORCE/src/heron.py/create_componentsets_in_HERON` function is called with a HERON xml input that does not contain a `<Components>` node, it will not respond with clarity. It prints that the components node is missing, then continues until it encounters an error when it tries to reference the unassigned `heron_comp_list` variable and gives an unhelpful error message. 

### Steps to Reproduce

- Create xml file with contents: `<HERON></HERON>`
- Call `FORCE/src/heron.py/create_componentsets_in_HERON(<any_comp_sets_folder>, <my_xml>)` where `my_xml` is the file created above

### Expected Behavior

Decisive behavior is preferred. Multiple options are available, including:
- `<Components>` node is created by the function
- An error is thrown
- The input is trusted and there is no check for whether the `<Components>` node exists

### Screenshots and Input Files

<img width="678" alt="Screenshot 2024-06-20 at 8 07 03 AM" src="https://github.com/idaholab/FORCE/assets/171727313/21a5a18d-f7a5-45d6-9769-07d46d920150">

![f818202e-c5d3-45f1-bb9f-7a8d290b7228](https://github.com/idaholab/FORCE/assets/171727313/8ae05009-4025-44ae-85b6-69d5c27da066)

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
@caleb-sitton-inl Can you please include as part of your issue the full error stack trace? It usually looks something like this:

![image](https://github.com/idaholab/FORCE/assets/15963026/944349f2-9f20-44df-a37f-18c666649fee)

**Comment by caleb-sitton-inl** [comment]
@dylanjm No problem!
