### ISSUE TITLE
[TASK] Create easily installable software packages for FORCE tools

### ISSUE THREAD

**Issue by j-bryan** [idaholab/FORCE#36]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
The installation process for various FORCE tools can be cumbersome. Not all users feel comfortable with terminal-based installation methods like cloning from GitHub to build from source or using pip to install RAVEN, HERON, TEAL, etc. Also, the NEAMS Workbench tool is a useful interface for FORCE tools but requires configuration to run HERON workflows.

**Describe the solution you'd like**
Package FORCE tools - particularly HERON, RAVEN, and TEAL - into a single installable package. Ideally, users will never need to interact with a terminal window. Also, bundling Workbench in this package can facilitate automated configuration of Workbench to run HERON workflows.

**Describe alternatives you've considered**
Docker container with FORCE tools, but this still requires reasonable comfort with command line utilities.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #37
